const toastMessage = {
  SUCCESS: "success",
  ERROR: "error",
  SUCCESS_TEXT: "Thành công! ",
  ERROR_TEXT: "Lỗi! ",
  ICON_SUCCESS: "icon-success",
  ICON_ERROR: "icon-error",
  SUCCESS_DELETE: "Công việc đã bị xoá.",
  ERROR_UPDATE_DATA: "Không thể cập nhật được dữ liệu.",
  SERVER_ERROR: "Có vấn đề phía máy chủ.",
  ERROR_GET_DEPARTMENTS: "Chưa lấy được các đơn vị.",
  TEXT_RED: "text-red",
  TEXT_GREEN: "text-green",
  ERROR_GET_NEW_EMPLOYEECODE: "Chưa lấy được mã nhân viên mới.",
  ERROR_SERVER: "Lỗi từ phía server.",
  ERROR_UPDATE_EMPLOYEE: "Không thể sửa nhân viên.",
  ERROR_ADD_EMPLOYEE: "Không thể thêm nhân viên.",
  SUCCESS_UPDATE_EMPLOYEE: "Nhân viên đã được sửa.",
  SUCCESS_ADD_EMPLOYEE: "Nhân viên đã được thêm.",
  SUCCESS_DELETE_EMPLOYEE: "Nhân viên đã được xoá",
  ERROR_DELETE_EMPLOYEE: `Các nhân viên chưa bị xoá.`,
  ERROR_DELETE_A_EMPLOYEE: "Nhân viên ${variable} chưa bị xoá.",
  SUCCESS_DELETE_A_EMPLOYEE: "Nhân viên ${variable} đã bị xoá.",
};

export default toastMessage;
